### ISSUE TITLE
Use of global variables

### ISSUE THREAD

**Issue by FrankD** [BennMacdonald/AGM_RPackage#11]
We currently use global variables ("<<-" assignment) to avoid having to recompute variables that are used at multiple points in the code. This is bad practice, and CRAN does not accept packages that change the global environment of the user. We need to rewrite the code to remove the use of global variables.

**Comment by FrankD** [comment]
PS: Once this issue is resolved we can in principle submit to CRAN, although I would also like to write a short vignette to show how to use the package.

**Comment by FrankD** [comment]
I have updated the code to remove the global variables, and replace them with variables that are passed around as part of `auxVars`. The package now passes all CRAN checks, and in principle we could submit it. However, as mentioned above, I would like to write a short vignette to show people how to use it; this should not take too long.

**Comment by BennMacdonald** [comment]
That is brilliant, Frank! Glad we are getting close to submitting. I am happy to wait off for the vignette. What kind of thing did you have in mind to include?

**Comment by BennMacdonald** [comment]
Hi Frank,

I am going to start writing the vignette today. What kind of thing did you have in mind for it? Something including:


·         A synopsis of what the function agm.R does

·         What adaptive gradient matching is

·         The difference between tempering of mismatch parameter and inferring

·         A worked example of the function

Anything else you were thinking of?






Regards,
Dr Benn Macdonald

Biometrika Fellow
University of Glasgow
School of Mathematics and Statistics
Room 225
G12 8SQ

**Comment by FrankD** [comment]
Hi Benn,

If you look at the latest commits, you'll see I've already started on the
vignette, but please go ahead and develop it further since I won't have
much more time this week to work on it.

In particular, it would be good if you could write something describing the
tempering scheme, and an example of how to use it.

Let me know if you encounter any issues!

Regards,

Frank

**Comment by BennMacdonald** [comment]
Thanks, Frank. I will do just that.






Regards,
Dr Benn Macdonald

Biometrika Fellow
University of Glasgow
School of Mathematics and Statistics
Room 225
G12 8SQ

**Comment by BennMacdonald** [comment]
Just to be clear (poor wording) – “I will do just that” meant that I will do as you suggest below. I do not mean “that is the only thing I will do”






Regards,
Dr Benn Macdonald

Biometrika Fellow
University of Glasgow
School of Mathematics and Statistics
Room 225
G12 8SQ
