### ISSUE TITLE
odeVGModel4Full

### ISSUE THREAD

**Issue by FrankD** [BennMacdonald/AGM_RPackage#12]
In function `odeVGModel4Full`, there is a term "Species[7]" in the second equation of the ODE:

    - params[2]*X[1]*X[3] + params[3]*X[4] + 
         params[7]*Species[7]

I think this should be `X[7]`, and have corrected it as such, but just wanted to make sure that I'm not overlooking anything.
On a more practical note, do we leave these functions in for the package? Since users can specify their own ODE functions, it's only useful if we want to use it for some of the examples, but I think we could actually get rid of them and just define temporary functions for the examples and vignette.

**Comment by BennMacdonald** [comment]
It absolutely should be X. I copied and changed some older files I was using, and must have missed this one, cheers!
We don't need to include these functions, now that users can specify their own. It might be nice to include any we use in examples. Furthermore, once I finish a paper I am working on for model selection, we could update the package to do this as well, in which case, we may want to use the VG models as examples. We can cross that bridge when we come to it though.

**Comment by FrankD** [comment]
I removed the files defining specific ODE models for now, we can always put them back in/retrieve them from the git repository if we need them later on.
