### ISSUE TITLE
Plotting Issue

### ISSUE THREAD

**Issue by BennMacdonald** [BennMacdonald/AGM_RPackage#14]
I was playing around with the example in the vignette and I noticed a problem with the plotting. See figure 1:

![test lv_func plotting problem](https://user-images.githubusercontent.com/26483161/27592393-4919f7c4-5b4c-11e7-9009-eb4d175635d4.png)

You can see in the bottom right panel (species 2), the signal is pretty flat. I think that this is a plotting problem rather than actual flattening. See figure 2:

![test lv_func recorded gp species 2](https://user-images.githubusercontent.com/26483161/27592407-539e99e8-5b4c-11e7-8a5d-ee9937ed0189.png)

Figure 2 is the recorded GP for species 2, saved after the MCMC has finished. You can see that the signal is not flat.

I can look into this, but will need to do so later. If you know what the issue is (since you changed the function that plots recently), can you either give me a quick direction as to the problem or edit yourself. If you don't know, don't worry, as I will investigate it later on.

Cheers.

**Comment by FrankD** [comment]
Good find Ben, although it's not a plotting issue (I'm not sure how you obtained the second plot, but the observed data points did not agree with the sampled latent GP values when I ran it). 

What happened was that I missed a subscript in the initialization, and so the initial values for the stored variables noiseA.u, K.u (cholesky decompositions) were calculated with the wrong GP hyperparameters. As a consequence, the code calculated an log likelihood for the initial state that was much too small, and so accepted the first change to GP hyperparameters that was proposed, even though it's detrimental.

It should be fixed now, but do let me know if you spot any other issues.
