### ISSUE TITLE
Start finalizing for CRAN submission

### ISSUE THREAD

**Issue by FrankD** [BennMacdonald/AGM_RPackage#16]
I think the package is now close to ready to be put on CRAN. Left to do:

- [x] Check and amend documentation.
- [x] Check it passes all the CRAN tests.
- [x] Change output -- I want the AGM function to return parameter estimates as well as saving them to disk, so that the user can do an analysis straight-away without having to load in a file.

**Comment by BennMacdonald** [comment]
Output can now be returned, as well as saving the results to disk. If you want other results to be returned (at the moment it returns parameter estimates and the log likelihood of top chain), we can include them as well. Will now check (and amend if necessary) the documentation.

**Comment by FrankD** [comment]
Finished and submitted a while ago. Can be found on CRAN here: https://cran.r-project.org/web/packages/deGradInfer/index.html
