### ISSUE TITLE
test branch is the default branch on the github page

### ISSUE THREAD

**Issue by FrankD** [BennMacdonald/AGM_RPackage#3]
Can you change this please Benn? It should be in the settings for the repository.

**Comment by BennMacdonald** [comment]
Sure. Would you prefer the master branch or the folder deGradInfer?

**Comment by BennMacdonald** [comment]
Changed to master. At moment, no option for deGradInfer. Guess it does not count as a branch?

**Comment by FrankD** [comment]
Thanks! Branches and folders are distinct, the main github page will always display the top level folder.
